let valor = parseInt(gets());
console.log(valor);
var nota = parseInt(valor / 100);
console.log(nota + " nota(s) de R$ 100,00");
var resto = valor % 100;
var nota = parseInt(resto / 50);
console.log(nota + " nota(s) de R$ 50,00");
var resto = resto % 50;
var nota = parseInt(resto / 20);
console.log(nota + " nota(s) de R$ 20,00");
var resto = resto % 20;
var nota = parseInt(resto / 10);
console.log(nota + " nota(s) de R$ 10,00");
var resto = resto % 10;
var nota = parseInt(resto / 5);
console.log(nota + " nota(s) de R$ 5,00");
var resto = resto % 5;
var nota = parseInt(resto / 2);
console.log(nota + " nota(s) de R$ 2,00");
var resto = resto % 2;
console.log(resto + " nota(s) de R$ 1,00");